packages:
  - ui/**/*
  - bin

catalog:
  '@badrap/result': 0.2.13
  breakpoint-sass: github:WandererXII/breakpoint#4.1
  shogiground: ^0.10.3
  shogiops: ^0.19.0
  snabbdom: ^3.6.3

minimumReleaseAge: 1440

onlyBuiltDependencies:
  - esbuild

savePrefix: ''
