export default {
  multipass: true,
  plugins: [
    // default:
    'removeDoctype',
    'removeXMLProcInst',
    'removeComments',
    'removeDeprecatedAttrs',
    'removeMetadata',
    'removeEditorsNSData',
    'cleanupAttrs',
    'mergeStyles',
    'inlineStyles',
    'minifyStyles',
    'cleanupIds',
    'removeUselessDefs',
    'cleanupNumericValues',
    'convertColors',
    {
      name: 'removeUnknownsAndDefaults',
      params: {
        unknownContent: true,
        unknownAttrs: true,
        defaultAttrs: true,
        defaultMarkupDeclarations: true,
        uselessOverrides: true,
        keepDataAttrs: false,
        keepAriaAttrs: false,
        keepRoleAttr: false,
      },
    },
    'removeNonInheritableGroupAttrs',
    'removeUselessStrokeAndFill',
    'cleanupEnableBackground',
    'removeHiddenElems',
    'removeEmptyText',
    'convertShapeToPath',
    'convertEllipseToCircle',
    'moveElemsAttrsToGroup',
    'moveGroupAttrsToElems',
    'collapseGroups',
    'convertPathData',
    'convertTransform',
    'removeEmptyAttrs',
    'removeEmptyContainers',
    'mergePaths',
    'removeUnusedNS',
    'sortAttrs',
    'sortDefsChildren',
    'removeDesc',
    // not default:
    'convertOneStopGradients',
    'convertStyleToAttrs',
    'cleanupListOfValues',
    {
      name: 'removeAttrs',
      params: {
        attrs: ['font-weight', 'font-size', 'font-family', 'letter-spacing', 'word-spacing'],
      },
    },
    'prefixIds',
    'removeScripts',
    'removeTitle',
  ],
};
